name: Build

on: push

jobs:
  backend-build:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: apps/backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Generate database types
        working-directory: libs/database
        run:
          npx prisma generate

      - name: Run type check
        run:
          npm run check

  frontend-build:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: apps/frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Generate database types
        working-directory: libs/database
        run:
          npx prisma generate

      - name: Run type check
        run:
          npm run build

  prettier:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Run type check
        run:
          npm run prettier

  eslint:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Generate database types
        working-directory: libs/database
        run:
          npx prisma generate

      - name: Run eslint check
        run:
          npm run lint