name: Build

on: push

env:
  # This is just a dummy URL for generating prisma schema; it won't be used.
  DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres

jobs:
  database-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: Install dependencies
        run: npm ci
      - name: Generate database types
        run: npm run schema-generate
      - name: Run build
        run: npm run build -w libs/database

  backend-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: Install dependencies
        run: npm ci
      - name: Generate database types
        run: npm run schema-generate
      - name: Build database client
        run: npm run build -w libs/database
      - name: Run type check
        run: npm run check -w apps/backend

  frontend-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: Install dependencies
        run: npm ci
      - name: Generate database types
        run: npm run schema-generate
      - name: Run build
        run: npm run build -w apps/frontend

  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: Install dependencies
        run: npm ci
      - name: Run style check
        run: npm run prettier

#  For now, eslint check is disabled due to some weird errors.
#  We should eventually figure out why they occur, but not today.
#  eslint:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v4
#      - name: Set up Node.js
#        uses: actions/setup-node@v6
#        with:
#          node-version: 24
#      - name: Install dependencies
#        run: npm ci
#      - name: Generate database types
#        working-directory: libs/database
#        run: npm run schema-generate
#      - name: Build database client
#        run: npm run build -w libs/database
#      - name: Run eslint check
#        run: npm run lint