name: Generate Docker Containers

on:
  push:
    tags:
      - '*'

jobs:
  backend:
    name: Build backend image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build image
        working-directory: backend
        run: docker build -t daemontus/bbm-backend .
        