name: Generate Docker Containers

on:
  push:
    tags:
      - '*'

jobs:
  database:
    name: Build backend database
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: "postgresql://postgres:postgres@localhost:5555/postgres"
    defaults:
      run:
        working-directory: libs/database
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Start database
        run: |
          docker run -d \
          --name my-db \
          -p 5555:5432 \
          -e PGDATA=/data \
          -e POSTGRES_USER=postgres \
          -e POSTGRES_PASSWORD=postgres \
          -e POSTGRES_DB=postgres \
          postgres:16
      - name: Init DB with prisma
        run: npx prisma migrate dev --name init
      - name: Seed DB with data
        run: npm run seed
      - name: Commit current state of the container
        run: docker commit my-db daemontus/bbm-database:latest
      - name: Push image
        run: docker push daemontus/bbm-database

  backend:
    name: Build backend image
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build image
        run: docker build --tag daemontus/bbm-backend --file ./Dockerfile
      - name: Push image
        run: docker push daemontus/bbm-backend

  frontend:
    name: Build frontend image
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Add Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: npm install
      - name: Build frontend
        run: npm run build
      - name: Build image
        run: docker build --tag daemontus/bbm-frontend --file ./Dockerfile
      - name: Push image
        run: docker push daemontus/bbm-frontend