name: Generate Docker Containers

on:
  push:
    tags:
      - '*'

jobs:
  database:
    name: Build backend database
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: "postgresql://bbm:bbm@localhost:5555/bbm?schema=public"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Start database
        run: docker compose -f ./docker-compose.dev-db.yml up -d
      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: Install dependencies
        run: npm ci
      - name: Init DB with prisma and automatically seed
        run: npm run schema-generate
      - name: Init DB with prisma and automatically seed
        run: npm run schema-migrate
      - name: Init DB with prisma and automatically seed
        run: npm run database-seed
      - name: Commit current state of the container
        run: docker commit bbm-database daemontus/bbm-database:latest
      - name: Push image
        run: docker push daemontus/bbm-database

  backend:
    name: Build backend image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build image
        run: docker build --tag daemontus/bbm-backend --file ./apps/backend/Dockerfile .
      - name: Push image
        run: docker push daemontus/bbm-backend

  frontend:
    name: Build frontend image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build image
        run: docker build --tag daemontus/bbm-frontend --file ./apps/frontend/Dockerfile .
      - name: Push image
        run: docker push daemontus/bbm-frontend